name: Deploy
on:
    release:
        types: [published]
jobs:
    release:
        name: Release
        runs-on: ubuntu-18.04
        steps:
            -
                name: Checkout
                uses: actions/checkout@v1
            -
                name: Deploy
                run: echo deploy ....
